### ISSUE TITLE
how does it work?

### ISSUE THREAD

**Issue by jtkeyva** [maxal-studio/flutter-plugin-camera360#3] opened 2024-01-16 19:05 UTC
i don't see any option to start "recording" or capturing? i can't tell what to do and how to start/stop it. then what happens?
thx

**Comment by dajanvulaj** [comment] 2024-01-16 19:19
There is no need to start/stop or record. You just point the camera at the dot and the dot will keep moving to the right till you do a 360 rotation. Then it will automatically stitch the images and return back a 360 panorama.

If you are using android, you might not be able to select a wide ange camera (This is a features missing from the official camera package by flutter)

On iPhone devices the wide angle camera for iPhone 11 and newer is the camera with key 2.

**Comment by jtkeyva** [comment] 2024-01-17 03:37
the dot did not move for me on ios. i thought i was missing some trigger that started it. so in the example as soon as it runs it's waiting to point the camera on the dot? it's confusing. thank you

**Comment by dajanvulaj** [comment] 2024-01-17 12:00
Please if you have any suggestions on how to improve the UI let us know by writing us an email at : **info@max.al** . We used this UI as it is currently used by the top rated 360 camera apps on the iOS/android market.

I’m closing this issue as this is not a bug.

**Closed by dajanvulaj** 2024-01-17 12:00 UTC

**Comment by jtkeyva** [comment] 2024-01-18 01:23
i think there should be a trigger/button to begin and end the panorama.
there should be an indicator while it is "recording"
there should be an arrow guiding you which way to move

when stopping the "recording" it should provide some feedback such as "processing"

i understand it's probably out of the scope of work to have a real-time stitching preview being generated as you pan but that would be cool like it does on iphone
